### ISSUE TITLE
SpecializedTinkerEdge.properties should filter out Property.empty[A] instances

### ISSUE THREAD

**Issue by jeremysears** [ShiftLeftSecurity/tinkergraph-gremlin#12]
The implementation of SpecializedTinkerEdge.properties differs from the reference implementation in the case when a single key is supplied and the value associated with that key is unset.  In this case, it should return an empty Iterator, instead of returning an Iterator containing a Property.empty[A] instance.  

See:
https://github.com/apache/tinkerpop/blob/master/tinkergraph-gremlin/src/main/java/org/apache/tinkerpop/gremlin/tinkergraph/structure/TinkerEdge.java#L138

**Comment by jeremysears** [comment]
Here's a stack trace for future reference.  This would trigger for `g.E().value("foo")` if any matching edge did not contain a value for property "foo".
```
java.lang.IllegalStateException: The property does not exist as it has no key, value, or associated element
	at org.apache.tinkerpop.gremlin.structure.Property$Exceptions.propertyDoesNotExist(Property.java:151)
	at org.apache.tinkerpop.gremlin.structure.util.empty.EmptyProperty.value(EmptyProperty.java:45)
	at org.apache.tinkerpop.gremlin.structure.Element.lambda$values$2(Element.java:107)
	at org.apache.tinkerpop.gremlin.util.iterator.IteratorUtils$3.next(IteratorUtils.java:247)
	at org.apache.tinkerpop.gremlin.process.traversal.step.map.FlatMapStep.processNextStart(FlatMapStep.java:45)
	at org.apache.tinkerpop.gremlin.process.traversal.step.util.AbstractStep.next(AbstractStep.java:128)
	at org.apache.tinkerpop.gremlin.process.traversal.step.util.AbstractStep.next(AbstractStep.java:38)
	at org.apache.tinkerpop.gremlin.process.traversal.Traversal.fill(Traversal.java:179)
	at org.apache.tinkerpop.gremlin.process.traversal.Traversal.toList(Traversal.java:117)
	at gremlin.scala.GremlinScala.toList(GremlinScala.scala:60)
```
