### ISSUE TITLE
SpecializedTinkerEdge support to delete edge?

### ISSUE THREAD

**Issue by zhuguocheng29** [ShiftLeftSecurity/tinkergraph-gremlin#40]
I use the query to delete "Action" edge as below: 
**g.V().outE("Action").drop().iterate();**

However it occurs some error. There are stack trace:

java.util.ConcurrentModificationException
        at java.util.ArrayList$Itr.next(ArrayList.java:860)
        at org.apache.tinkerpop.gremlin.util.iterator.MultiIterator.next(MultiIterator.java:72)
        at org.apache.tinkerpop.gremlin.process.traversal.step.map.FlatMapStep.processNextStart(FlatMapStep.java:45)
        at org.apache.tinkerpop.gremlin.process.traversal.step.util.AbstractStep.hasNext(AbstractStep.java:143)
        at org.apache.tinkerpop.gremlin.process.traversal.step.util.ExpandableStepIterator.next(ExpandableStepIterator.java:50)
        at org.apache.tinkerpop.gremlin.process.traversal.step.filter.FilterStep.processNextStart(FilterStep.java:37)
        at org.apache.tinkerpop.gremlin.process.traversal.step.util.AbstractStep.hasNext(AbstractStep.java:143)
        at org.apache.tinkerpop.gremlin.process.traversal.step.util.ExpandableStepIterator.next(ExpandableStepIterator.java:50)
        at org.apache.tinkerpop.gremlin.process.traversal.step.filter.FilterStep.processNextStart(FilterStep.java:37)
        at org.apache.tinkerpop.gremlin.process.traversal.step.util.AbstractStep.next(AbstractStep.java:128)
        at org.apache.tinkerpop.gremlin.process.traversal.step.util.AbstractStep.next(AbstractStep.java:38)
        at org.apache.tinkerpop.gremlin.process.traversal.Traversal$-CC.$default$iterate(Traversal.java:203)
        at org.apache.tinkerpop.gremlin.process.traversal.dsl.graph.GraphTraversal$-CC.$default$iterate(GraphTraversal.java:2704)
        at org.apache.tinkerpop.gremlin.process.traversal.dsl.graph.GraphTraversal$Admin$-CC.$default$iterate(GraphTraversal.java:179)
        at org.apache.tinkerpop.gremlin.process.traversal.dsl.graph.DefaultGraphTraversal.iterate(DefaultGraphTraversal.java:48)

**Comment by mpollmeier** [comment]
yup that's currently not supported, and we're making some fundamental changes at the moment, so I'd recommend to not base any work on this at the moment. we'll fork off a version of this that can live on it's own.

**Comment by zhuguocheng29** [comment]
@mpollmeier But we urgently need this feature now. Can I add it myself? Could you tell me where to add this?

**Comment by zhuguocheng29** [comment]
@mpollmeier Could you tell me when you support the feature of  edge deletion and withComputer methods?

**Comment by mpollmeier** [comment]
You could fork this repo from version v3.3.4.18 https://github.com/ShiftLeftSecurity/tinkergraph-gremlin/releases/tag/v3.3.4.18 and add the feature yourself.
